git submodule add -b 11.0 https://github.com/itdurpro/account-financial-reporting/
git submodule add -b 11.0 https://github.com/itdurpro/account-financial-tools/
git submodule add -b 11.0 https://github.com/itdurpro/account-payment/
git submodule add -b 11.0 https://github.com/itdurpro/bank-payment/
git submodule add -b 11.0 https://github.com/itdurpro/commission/
git submodule add -b 11.0 https://github.com/itdurpro/crm/
git submodule add -b 11.0 https://github.com/itdurpro/currency/
git submodule add -b 11.0 https://github.com/itdurpro/delivery-carrier/
git submodule add -b 11.0 https://github.com/itdurpro/hr/
git submodule add -b 11.0 https://github.com/itdurpro/knowledge/
git submodule add -b 11.0 https://github.com/itdurpro/product-attribute/
git submodule add -b 11.0 https://github.com/itdurpro/purchase-workflow/
git submodule add -b 11.0 https://github.com/itdurpro/reporting-engine/
git submodule add -b 11.0 https://github.com/itdurpro/sale-workflow/
git submodule add -b 11.0 https://github.com/itdurpro/server-tools/
git submodule add -b 11.0 https://github.com/itdurpro/server-ux/
git submodule add -b 11.0 https://github.com/itdurpro/stock-logistics-workflow/
git submodule add -b 11.0 https://github.com/itdurpro/web/
git submodule add -b 11.0 https://github.com/itdurpro/website/
